blank_issues_enabled: false
contact_links:
  - name: Community Forum
    url: https://community.homey.app/t/app-pro-fusionsolar-openapi/153353
    about: Ask questions or share feedback on the Homey Community Forum
